theme: jekyll-theme-merlot
title: Database Management System
description:    DBMS is a programming language with the intention to facilitate back-end creation for various purposes and emulate the functionality of a database system. 
